# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a6a1be3c09ff10d472bf44f8efe939f4ebab70d193fc58bdf9a2a6fd2ffc4706901125d9a5b99f751d17d82590ffb0577d02d2033c89df3d84f48cc1677a491

test:
  secret_key_base: ecff0c62da47b26296e6b3c76a4e82f040e5cc3e3ed77e9e0b09a9098afa6068ad0e0d841c682d51b35628161e7d4e21f8c381d626f52073a22c427515dac5ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
