source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'puma'
gem 'rails'

group :development, :test do
  gem 'rspec-rails'
end

group :development do
  gem 'awesome_print'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'irbtools', require: 'irbtools/binding'
  gem 'listen'
  gem 'meta_request'

  # Code quality
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'fasterer', require: false
  gem 'mdl', require: false
  gem 'overcommit', require: false
  gem 'rails_best_practices', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
end
